"""VoiceHaul demo: one command, no API keys, no network, ~15 seconds.

    py -3 run_demo.py

Every number printed below is computed from the run. Nothing is hard-coded.
"""

import argparse
import random
import sys
import time
from typing import Dict, List

from voicehaul.policies import (CalibratedPolicy as CalibratedAgent,
                                DrifterPolicy as DrifterAgent,
                                FlatPolicy as FlatAgent,
                                MirrorPolicy as MirrorAgent,
                                OraclePolicy as OracleAgent)
from voicehaul.env import PERSONAS
from voicehaul import metrics as M
from voicehaul.onset import false_positive_rate, localize, score_localization
from voicehaul.runner import run_episode

LINE = "-" * 78
AGENTS = [("mirror", MirrorAgent), ("flat_cheerful", FlatAgent),
          ("drifter", DrifterAgent), ("calibrated", CalibratedAgent),
          ("oracle", OracleAgent)]


def header(n, title: str) -> None:
    print("\n" + LINE)
    print("[{}] {}".format(n, title))
    print(LINE)


def build_suite(agent_cls, n_episodes: int, n_turns: int, corrupt_p: float = 0.0):
    eps, cases = [], []
    for i in range(n_episodes):
        persona = PERSONAS[i % len(PERSONAS)]
        ep = run_episode(agent_cls(), persona, seed=i, n_turns=n_turns,
                         corrupt_p=corrupt_p)
        eps.append(ep)
        cases.append((ep, persona))
    return eps, cases


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--episodes", type=int, default=30)
    ap.add_argument("--turns", type=int, default=40)
    ap.add_argument("--no-plot", action="store_true")
    args = ap.parse_args()
    t0 = time.time()

    print(LINE)
    print("VOICEHAUL - long-horizon evaluation for empathic voice agents")
    print(LINE)
    print("suite      : {} personas x {} episodes x {} turns = {:,} scored turns"
          .format(len(PERSONAS), args.episodes, args.turns,
                  args.episodes * args.turns))
    print("personas   : " + ", ".join(p.name for p in PERSONAS))
    print("guarantees : no network, no API key, deterministic under a fixed seed")

    suites: Dict[str, list] = {}
    case_sets: Dict[str, list] = {}
    for name, cls in AGENTS:
        suites[name], case_sets[name] = build_suite(cls, args.episodes, args.turns)

    # held-out states for the fixed-context panel, generated by a reference
    # policy so no agent is scored on a distribution it created itself
    ref = [run_episode(OracleAgent(), PERSONAS[i % len(PERSONAS)], seed=500 + i,
                       n_turns=args.turns) for i in range(args.episodes)]
    panel_states = [(t.index, t.user_before) for ep in ref for t in ep.turns][::3]

    # ------------------------------------------------------------------ [1] --
    header(1, "THE SAME MODELS, RANKED TWO WAYS")
    print("left  : a fixed-context turn panel. Every agent answers the same {}"
          .format(len(panel_states)))
    print("        held-out user states, each turn rated on its own - how a")
    print("        prompt-set leaderboard works.")
    print("right : the same agents actually holding {}-turn conversations."
          .format(args.turns))
    print()
    print("{:<15}{:>12}{:>13}{:>14}{:>12}".format(
        "agent", "panel:", "panel:", "conversation:", "conv:"))
    print("{:<15}{:>12}{:>13}{:>14}{:>12}".format(
        "", "perceived", "calibration", "left-over", "fail rate"))
    print("{:<15}{:>12}{:>13}{:>14}{:>12}".format(
        "", "empathy", "", "distress", ""))
    panel_perc, outcome = [], []
    for name, cls in AGENTS:
        p, c = M.turn_panel(cls, panel_states)
        tl = M.tail_load(suites[name])
        fr = M.failure_rate(suites[name])
        panel_perc.append(p)
        outcome.append(-tl)                      # higher is better, both axes
        print("{:<15}{:>12.3f}{:>13.3f}{:>14.3f}{:>11.0f}%".format(
            name, p, c, tl, 100 * fr))

    rho = M.spearman(panel_perc, outcome)
    best_panel = AGENTS[panel_perc.index(max(panel_perc))][0]
    best_conv = AGENTS[outcome.index(max(outcome))][0]
    print()
    print("  turn panel says the best model is : {}".format(best_panel))
    print("  the conversations say it is       : {}".format(best_conv))
    print("  rank correlation between the two  : rho = {:+.2f}".format(rho))
    print()
    print("  The two rankings are anti-correlated. Not because turn-level rating")
    print("  is wrong, but because it holds the context fixed - and in a real")
    print("  conversation the model creates the context it is later scored on.")

    # ------------------------------------------------------------------ [2] --
    header(2, "WHICH USERS IT BREAKS ON")
    print("Left-over distress by persona. An aggregate score hides this; a")
    print("regression that only hits angry callers is still a regression.")
    print()
    print("{:<15}".format("agent") + "".join(
        "{:>13}".format(p.name[:12]) for p in PERSONAS))
    for name, _ in AGENTS:
        row = ""
        for p in PERSONAS:
            sub = [e for e in suites[name] if e.persona == p.name]
            row += "{:>13.2f}".format(M.tail_load(sub))
        print("{:<15}".format(name) + row)
    mh = M.tail_load([e for e in suites["mirror"] if e.persona == "hostile_escalation"])
    ch = M.tail_load([e for e in suites["calibrated"]
                      if e.persona == "hostile_escalation"])
    print()
    print("  mirroring is near-harmless on calm users and {:.1f}x worse than the"
          .format(mh / ch if ch else float("nan")))
    print("  calibrated policy on hostile ones. That is the actionable sentence.")

    # ------------------------------------------------------------------ [3] --
    header(3, "FEEDBACK UPTAKE: DOES A REQUEST SURVIVE THE CONVERSATION?")
    print("Share of explicit user requests (\"slow down\", \"stop apologising\", ...)")
    print("still honoured N turns after the user made them.")
    print()
    print("{:<15}{:>9}{:>9}{:>9}{:>9}{:>14}".format(
        "agent", "FUR@1", "FUR@5", "FUR@10", "FUR@20", "half-life"))
    uptake_curves = {}
    for name, _ in AGENTS:
        u = M.feedback_uptake(suites[name])
        hl = M.uptake_half_life(suites[name])
        uptake_curves[name] = M.feedback_uptake(
            suites[name], lags=list(range(1, 26)))
        if hl != hl:
            hl_s = "n/a"
        elif hl == float("inf"):
            hl_s = "no decay" if u[20] >= 0.9 * u[1] else "> 30 turns"
        else:
            hl_s = "{:.1f} turns".format(hl)
        print("{:<15}{:>9.2f}{:>9.2f}{:>9.2f}{:>9.2f}{:>14}".format(
            name, u[1], u[5], u[10], u[20], hl_s))
    du = M.feedback_uptake(suites["drifter"])
    print()
    print("  drifter honours {:.0%} of requests immediately and {:.0%} twenty turns"
          .format(du[1], du[20]))
    print("  later, at an unchanged turn-level score. Only the lag exposes it.")

    # ------------------------------------------------------------------ [4] --
    header(4, "MIMICRY VS REGULATION")
    print("mimicry    = corr(agent vocal energy, user arousal)   -> sounds attuned")
    print("regulation = negative affect removed per turn (x100)  -> actually helps")
    print()
    print("{:<15}{:>12}{:>16}{:>10}".format(
        "agent", "mimicry r", "regulation", "MAI"))
    mr = {}
    for name, _ in AGENTS:
        m, r = M.mimicry_and_regulation(suites[name])
        mr[name] = (m, r)
        print("{:<15}{:>+12.2f}{:>16.2f}{:>10.2f}".format(
            name, m, r, M.mimicry_adaptation_index(m, r)))
    orders = set()
    for k in (1.0, 2.0, 3.0, 4.0):
        orders.add(tuple(sorted(mr, key=lambda n: -M.mimicry_adaptation_index(
            mr[n][0], mr[n][1], k))))
    print()
    print("  the mirror tracks the user ({:+.2f}); the calibrated policy moves"
          .format(mr["mirror"][0]))
    print("  against them ({:+.2f}) and removes {:.0f}% more distress per turn."
          .format(mr["calibrated"][0],
                  100 * (mr["calibrated"][1] / mr["mirror"][1] - 1)))
    print("  MAI ranking is {} for k in [1, 4] ({} distinct ordering{}).".format(
        "stable" if len(orders) == 1 else "NOT stable", len(orders),
        "" if len(orders) == 1 else "s"))

    # ------------------------------------------------------------------ [5] --
    header(5, "CORRUPTED FEEDBACK: WHEN THE CHANNEL ITSELF IS WRONG")
    print("A share of user requests reach the model as the opposite instruction")
    print("(ASR error, or an adversarial user). The user still expects the original.")
    print()
    print("{:<15}{:>14}{:>14}{:>14}{:>12}".format(
        "agent", "clean FUR@10", "20% corrupt", "40% corrupt", "drop"))
    for name, cls in AGENTS:
        if name == "oracle":
            continue
        clean = M.feedback_uptake(suites[name])[10]
        row = []
        for cp in (0.2, 0.4):
            eps, _ = build_suite(cls, args.episodes, args.turns, corrupt_p=cp)
            row.append(M.feedback_uptake(eps)[10])
        print("{:<15}{:>14.2f}{:>14.2f}{:>14.2f}{:>11.1f}p".format(
            name, clean, row[0], row[1], 100 * (row[1] - clean)))
    print()
    print("  the agents that listen best degrade most: perfect compliance with a")
    print("  corrupted channel is itself a failure mode, and it is invisible to")
    print("  any suite whose feedback channel is assumed clean.")

    # ------------------------------------------------------------------ [6] --
    header(6, "FAILURE-ONSET LOCALIZATION")
    print("A regression is injected at a known turn: the model loses its")
    print("conditioning and reverts to a generic upbeat persona. The task is to")
    print("name that turn from the conversation alone. Cheap deterministic")
    print("diagnostics propose candidates; counterfactual replay confirms cause.")
    print()
    print("{:<14}{:>14}{:>12}{:>12}{:>16}".format(
        "fault severity", "conversations", "top-1", "top-3", "median error"))
    for sev in (1.0, 0.7, 0.5, 0.35):
        rng = random.Random(11)
        faulted = []
        for i in range(args.episodes):
            persona = PERSONAS[i % len(PERSONAS)]
            ft = rng.randrange(6, args.turns - 8)
            faulted.append((run_episode(CalibratedAgent(), persona, seed=2000 + i,
                                        n_turns=args.turns, fault_turn=ft,
                                        fault_severity=sev), persona))
        r = score_localization(faulted, tolerance=1)
        print("{:<14}{:>14}{:>11.1f}%{:>11.1f}%{:>16}".format(
            "{:.2f}".format(sev), r["n"], 100 * r["top1"], 100 * r["top3"],
            "{:+.0f} turns".format(r["median_signed_error"])))
        if sev == 1.0:
            ex = next((c for c in faulted if c[0].failed), None)

    fp = false_positive_rate(case_sets["calibrated"])
    print()
    print("  false positives on healthy runs : {:.1%}  (n={})".format(
        fp, len(case_sets["calibrated"])))
    print("  severity 1.00 is a full reversion; 0.35 blends the degraded persona")
    print("  into the model's own policy, which is the realistic case. Accuracy")
    print("  should always be reported against it, never as a single number.")
    if ex:
        onset, ranked = localize(ex[0], ex[1])
        print()
        print("  example: persona={}  true fault turn={}  predicted={}".format(
            ex[0].persona, ex[0].true_fault_turn, onset))
        print("  ranked candidates: {}".format(ranked[:5]))

    # ------------------------------------------------------------------ [7] --
    header(7, "HOW MANY CONVERSATIONS BEFORE A REGRESSION IS VISIBLE?")
    print("Human ratings are both the ground truth and the budget line. Between-")
    print("conversation spread is measured from this suite; rater noise is set to")
    print("0.9 Likert points. Two-sample, alpha=0.05, power=0.80.")
    print()
    per_conv = [1.0 + 6.0 * e.mean_perceived for e in suites["calibrated"]]
    sigma_between = M.stdev(per_conv)
    print("  measured between-conversation sd : {:.2f} Likert points".format(
        sigma_between))
    print()
    print("{:<24}{:>12}{:>12}{:>12}".format(
        "raters / conversation", "N=30", "N=100", "N=300"))
    for nr in (1, 3, 5):
        cells = ["{:.2f}".format(M.min_detectable_effect(sigma_between, 0.9, n, nr))
                 for n in (30, 100, 300)]
        print("{:<24}{:>12}{:>12}{:>12}".format(nr, *cells))
    print("  (cells are the smallest true regression, in Likert points, that the")
    print("   suite can detect at 80% power)")
    print()
    print("  a 30-conversation suite with 3 raters cannot see anything smaller")
    print("  than {:.2f} points; catching a 0.20-point regression needs N = {}."
          .format(M.min_detectable_effect(sigma_between, 0.9, 30, 3),
                  M.required_n(0.20, sigma_between, 0.9, 3)))

    if not args.no_plot:
        try:
            _plot(suites, uptake_curves, mr, panel_perc, outcome, rho, args)
            print("\nwrote voicehaul_report.png")
        except Exception as exc:                      # matplotlib is optional
            print("\n(plot skipped: {})".format(exc))

    print("\ndone in {:.1f}s".format(time.time() - t0))
    return 0


def _plot(suites, uptake_curves, mr, panel_perc, outcome, rho, args) -> None:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    colors = {"mirror": "#d1495b", "flat_cheerful": "#edae49",
              "drifter": "#8a6fbf", "calibrated": "#2a9d8f", "oracle": "#8d99ae"}
    fig, axes = plt.subplots(1, 4, figsize=(19, 4.3))

    ax = axes[0]
    offs = {"oracle": (7, -12), "calibrated": (7, 5)}
    for i, (name, _) in enumerate(AGENTS):
        ax.scatter(panel_perc[i], -outcome[i], s=130, color=colors[name], zorder=3)
        ax.annotate(name, (panel_perc[i], -outcome[i]), fontsize=8,
                    textcoords="offset points", xytext=offs.get(name, (7, 4)))
    ax.set_title("Turn panel vs outcome  (rho = {:+.2f})".format(rho))
    ax.set_xlabel("perceived empathy, fixed-context panel")
    ax.set_ylabel("left-over distress  (lower is better)")
    ax.grid(alpha=.25)

    ax = axes[1]
    for name, eps in suites.items():
        n = len(eps[0].turns)
        ax.plot(range(n), [M.mean([e.turns[t].calibration for e in eps])
                           for t in range(n)], color=colors[name], lw=1.9,
                label=name)
    ax.set_title("Calibration over a conversation")
    ax.set_xlabel("turn"); ax.set_ylabel("empathic calibration")
    ax.legend(fontsize=8, frameon=False); ax.grid(alpha=.25)

    ax = axes[2]
    for name, curve in uptake_curves.items():
        lags = sorted(curve)
        ax.plot(lags, [curve[l] for l in lags], color=colors[name], lw=1.9)
    ax.set_title("A user request stops being honoured")
    ax.set_xlabel("turns since the request"); ax.set_ylabel("compliance")
    ax.set_ylim(-0.03, 1.05); ax.grid(alpha=.25)

    ax = axes[3]
    offs4 = {"oracle": (7, -13), "calibrated": (7, 5)}
    for name, (m, r) in mr.items():
        ax.scatter(m, r, s=130, color=colors[name], zorder=3)
        ax.annotate(name, (m, r), fontsize=8, textcoords="offset points",
                    xytext=offs4.get(name, (7, 4)))
    ax.axhline(0, color="#999", lw=.8); ax.axvline(0, color="#999", lw=.8)
    ax.set_title("Sounding attuned is not helping")
    ax.set_xlabel("mimicry  (corr with user arousal)")
    ax.set_ylabel("regulation  (distress removed / turn)")
    ax.grid(alpha=.25)

    fig.suptitle("VoiceHaul - long-horizon evaluation for empathic voice agents "
                 "({} personas, {} episodes, {} turns)".format(
                     len(PERSONAS), args.episodes, args.turns), fontsize=11)
    fig.tight_layout(rect=(0, 0, 1, 0.93))
    fig.savefig("voicehaul_report.png", dpi=150)


if __name__ == "__main__":
    sys.exit(main())
